name: Starter Workflow Demo
on:
  pull_request_target:
    types:
      - ready_for_review
      - converted_to_draft
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        run: |
          JIRA_ISSUE=$(echo $(echo "${{ github.event.pull_request.head.ref }}" | cut -d'-' -f1-2))
          PR_DRAFT=$(echo ${{github.event.pull_request.draft}})
          echo "$JIRA_ISSUE"
          echo "$PR_DRAFT"
          WEBHOOK_URL="https://automation.atlassian.com/pro/hooks/6f0bbeb2cf0efd2f91e74e7150f11ad71ea61b92"
          curl -X POST "$WEBHOOK_URL" \
               --data '{"issues":["'"$JIRA_ISSUE"'"], "data": {"draft":"'"$PR_DRAFT"'"}}'
